spring:
  datasource:
    url: "{cipher}af24a7f5743583b66fe2eb6181f25a7b57ec11ae0c3e68d52af803502337595e33661ba40c9b1c724c1a9c9400d02bcb24e50f52dea0460f2136253b2971b10c7892695131afea51b51a5ca26d13ed9886b723bcfc931b8b544e85e25a27e55de379325c3241af2b14acf153e71a3174ce835c2fca943924d419b96ac7ac0f7a"
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-Vendas
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000        # 5 minutos
      max-lifetime: 1200000       # 20 minutos
      connection-timeout: 20000   # 20 segundos
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update           # Cuidado em produção, use 'validate' ou 'none'
    show-sql: true              # Desative em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false         # Boa prática para evitar problemas de performance
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher # resolvendo incomppatibilidade entre o springfox e o spring boot
    flyway:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/tetdata
      # table: MigrationHistory
      # default-schema: imomo
eureka:
  client:
    service-url:
      defaultZone: "{cipher}4c165731625cba53d0727f94ada1b0a447fde4331f2778c7457d90ed1e83c39a9603e35dfd0032ee3db43a34c5f2678d"

server:
  port: ${SERVER_PORT:0}                    # Porta da aplicação

# Configurações de logging
logging:
  level:
    org.hibernate.SQL: DEBUG          # Desative em produção
    org.hibernate.type.descriptor.sql: TRACE  # Desative em produção
    com.zaxxer.hikari: DEBUG         # Desative em produção
    org.springframework: INFO

# Configurações do actuator para monitoramento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
produto:
  name: "1233333"
