spring:
  datasource:
    url: "{cipher}b9d84cabf541bcb8affa53bdd54cd4a0e89d66514efc0ce124dc054014a180e704e263ad36fa88760b6ce039125a795dfd4ebe47280c1ac3ca2d4246488bd5e1d7422a3f87bb157e91ba10aeef1d5047c150444d00299fc88d966c2ed845fccc9caff2fbc8993e3842894687c5312c444271a3fbac3c1832c6b5030d027d43a7dff84129d829386b1d9208f5290284b3"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariPool-Vendas
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000        # 5 minutos
      max-lifetime: 1200000       # 20 minutos
      connection-timeout: 20000   # 20 segundos
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update           # Cuidado em produção, use 'validate' ou 'none'
    show-sql: true              # Desative em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false         # Boa prática para evitar problemas de performance
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher # resolvendo incomppatibilidade entre o springfox e o spring boot
    flyway:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/tetdata
      # table: MigrationHistory
      # default-schema: imomo
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
eureka:
  client:
    service-url:
      defaultZone: "{cipher}4c165731625cba53d0727f94ada1b0a447fde4331f2778c7457d90ed1e83c39a9603e35dfd0032ee3db43a34c5f2678d"

server:
  port: ${SERVER_PORT:0}                    # Porta da aplicação

# Configurações de logging
logging:
  level:
    org.hibernate.SQL: DEBUG          # Desative em produção
    org.hibernate.type.descriptor.sql: TRACE  # Desative em produção
    com.zaxxer.hikari: DEBUG         # Desative em produção
    org.springframework: INFO

# Configurações do actuator para monitoramento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
produto:
  name: "12345"