spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/venda

  jpa:
    hibernate:
      ddl-auto: update           # Cuidado em produção, use 'validate' ou 'none'
    show-sql: true              # Desative em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false         # Boa prática para evitar problemas de performance
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher # resolvendo incomppatibilidade entre o springfox e o spring boot
    flyway:
      enabled: true
      locations:
        - classpath:db/migration
        - classpath:db/tetdata
      # table: MigrationHistory
      # default-schema: imomo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: ${PORT:0}                    # Porta da aplicação

# Configurações de logging
logging:
  level:
    org.hibernate.SQL: DEBUG          # Desative em produção
    org.hibernate.type.descriptor.sql: TRACE  # Desative em produção
    com.zaxxer.hikari: DEBUG         # Desative em produção
    org.springframework: INFO

# Configurações do actuator para monitoramento
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

